from wazimap.data.tables import FieldTable, SimpleTable


# Define our tables so the data API can discover them.
FieldTable(['rural or urban', 'sex', 'age in completed years'])
#tz wards do not have population breakdown by age so they have a separate table
FieldTable(['rural or urban', 'sex'])
FieldTable(['employment activity status', 'sex'], universe='People aged 5 years and older')
FieldTable(['school attendance', 'sex'], universe='People aged 3 years and older')
FieldTable(['highest education level reached'], universe='People aged 3 years and older')
FieldTable(['main mode of human waste disposal'], universe='Households')
FieldTable(['main source of water'], universe='Households')
FieldTable(['main type of lighting fuel'], universe='Households')
FieldTable(['main type of floor material'], universe='Households')
FieldTable(['main type of wall material'], universe='Households')
FieldTable(['main type of roofing material'], universe='Households')
FieldTable(['literacy test'])
FieldTable(['pepfar'])
FieldTable(['school attendance'])
FieldTable(['pupil teacher ratios'])
FieldTable(['school amenity'])
FieldTable(['causes of death under five'])
FieldTable(['causes of death over five'])
FieldTable(['inpatient diagnosis over five'])
FieldTable(['inpatient diagnosis under five'])
FieldTable(['outpatient diagnosis over five'])
FieldTable(['outpatient diagnosis under five'])
FieldTable(['family planning clients'])
FieldTable(['place of delivery'])
FieldTable(['health workers'])
FieldTable(['health centers'])
FieldTable(['health center ownership'])
FieldTable(['hiv centers'])
FieldTable(['tetanus vaccine'])
FieldTable(['traffic and crimes'])
FieldTable(['primary school teachers'])
FieldTable(['water sources'])
