CREATE TABLE IF NOT EXISTS public.number_of_hospital_beds (
          geo_level TEXT,
geo_code TEXT,
geo_version NUMERIC,
parent_level TEXT,
parent_code TEXT,
name TEXT,
no_of_beds NUMERIC
);

INSERT INTO public.number_of_hospital_beds VALUES
    (NULL,NULL,NULL,NULL,NULL,'Ainabkoi',1324),
(NULL,NULL,NULL,NULL,NULL,'Ainamoi',880),
(NULL,NULL,NULL,NULL,NULL,'Aldai',108),
(NULL,NULL,NULL,NULL,NULL,'Alego Usonga',435),
(NULL,NULL,NULL,NULL,NULL,'Athi River',672),
(NULL,NULL,NULL,NULL,NULL,'Awendo',206),
(NULL,NULL,NULL,NULL,NULL,'Balambala',9),
(NULL,NULL,NULL,NULL,NULL,'Banissa',57),
(NULL,NULL,NULL,NULL,NULL,'Baringo Central',252),
(NULL,NULL,NULL,NULL,NULL,'Baringo North',51),
(NULL,NULL,NULL,NULL,NULL,'Belgut',67),
(NULL,NULL,NULL,NULL,NULL,'Bobasi',170),
(NULL,NULL,NULL,NULL,NULL,'Bomachoge Borabu',76),
(NULL,NULL,NULL,NULL,NULL,'Bomachoge Chache',205),
(NULL,NULL,NULL,NULL,NULL,'Bomet Central',225),
(NULL,NULL,NULL,NULL,NULL,'Bomet East',179),
(NULL,NULL,NULL,NULL,NULL,'Bonchari',131),
(NULL,NULL,NULL,NULL,NULL,'Bondo',418),
(NULL,NULL,NULL,NULL,NULL,'Borabu',216),
(NULL,NULL,NULL,NULL,NULL,'Bumula',143),
(NULL,NULL,NULL,NULL,NULL,'Bunyala',96),
(NULL,NULL,NULL,NULL,NULL,'Bura',38),
(NULL,NULL,NULL,NULL,NULL,'Bureti',515),
(NULL,NULL,NULL,NULL,NULL,'Butere',220),
(NULL,NULL,NULL,NULL,NULL,'Butula',85),
(NULL,NULL,NULL,NULL,NULL,'Buuri',179),
(NULL,NULL,NULL,NULL,NULL,'Changamwe',275),
(NULL,NULL,NULL,NULL,NULL,'Chepalungu',78),
(NULL,NULL,NULL,NULL,NULL,'Cheptais',98),
(NULL,NULL,NULL,NULL,NULL,'Cherangany',90),
(NULL,NULL,NULL,NULL,NULL,'Chesumei',202),
(NULL,NULL,NULL,NULL,NULL,'Chuka',254),
(NULL,NULL,NULL,NULL,NULL,'Dadaab',76),
(NULL,NULL,NULL,NULL,NULL,'Dagoretti North',563),
(NULL,NULL,NULL,NULL,NULL,'Dagoretti South',79),
(NULL,NULL,NULL,NULL,NULL,'East Pokot',58),
(NULL,NULL,NULL,NULL,NULL,'Eldas',0),
(NULL,NULL,NULL,NULL,NULL,'Embakasi Central',275),
(NULL,NULL,NULL,NULL,NULL,'Embakasi East',388),
(NULL,NULL,NULL,NULL,NULL,'Embakasi North',101),
(NULL,NULL,NULL,NULL,NULL,'Embakasi South',190),
(NULL,NULL,NULL,NULL,NULL,'Embakasi West',216),
(NULL,NULL,NULL,NULL,NULL,'Emgwen',244),
(NULL,NULL,NULL,NULL,NULL,'Emuhaya',59),
(NULL,NULL,NULL,NULL,NULL,'Endebess',44),
(NULL,NULL,NULL,NULL,NULL,'Fafi',161),
(NULL,NULL,NULL,NULL,NULL,'Galole',191),
(NULL,NULL,NULL,NULL,NULL,'Ganze',45),
(NULL,NULL,NULL,NULL,NULL,'Garbatulla',97),
('level1','KE_1_007',2009,'country','KE','Garissa',503),
(NULL,NULL,NULL,NULL,NULL,'Garsen',90),
(NULL,NULL,NULL,NULL,NULL,'Gatanga',65),
(NULL,NULL,NULL,NULL,NULL,'Gatundu North',108),
(NULL,NULL,NULL,NULL,NULL,'Gatundu South',275),
(NULL,NULL,NULL,NULL,NULL,'Gem',140),
(NULL,NULL,NULL,NULL,NULL,'Gilgil',502),
(NULL,NULL,NULL,NULL,NULL,'Githunguri',95),
(NULL,NULL,NULL,NULL,NULL,'Hamisi',173),
(NULL,NULL,NULL,NULL,NULL,'Homa Bay Town',462),
(NULL,NULL,NULL,NULL,NULL,'Hulugho',14),
(NULL,NULL,NULL,NULL,NULL,'Igambangombe',107),
(NULL,NULL,NULL,NULL,NULL,'Igembe Central',82),
(NULL,NULL,NULL,NULL,NULL,'Igembe North',66),
(NULL,NULL,NULL,NULL,NULL,'Igembe South',461),
(NULL,NULL,NULL,NULL,NULL,'Ijara',81),
(NULL,NULL,NULL,NULL,NULL,'Ikolomani',140),
(NULL,NULL,NULL,NULL,NULL,'Imenti Central',228),
(NULL,NULL,NULL,NULL,NULL,'Imenti North',422),
(NULL,NULL,NULL,NULL,NULL,'Imenti South',466),
('level1','KE_1_011',2009,'country','KE','Isiolo',571),
(NULL,NULL,NULL,NULL,NULL,'Jomvu',71),
(NULL,NULL,NULL,NULL,NULL,'Juja',130),
(NULL,NULL,NULL,NULL,NULL,'Kabete',207),
(NULL,NULL,NULL,NULL,NULL,'Kabondo Kasipul',185),
(NULL,NULL,NULL,NULL,NULL,'Kabuchai',203),
(NULL,NULL,NULL,NULL,NULL,'Kaiti',163),
(NULL,NULL,NULL,NULL,NULL,'Kajiado Central',257),
(NULL,NULL,NULL,NULL,NULL,'Kajiado East',371),
(NULL,NULL,NULL,NULL,NULL,'Kajiado North',372),
(NULL,NULL,NULL,NULL,NULL,'Kajiado West',81),
(NULL,NULL,NULL,NULL,NULL,'Kalama',22),
(NULL,NULL,NULL,NULL,NULL,'Kaloleni',218),
(NULL,NULL,NULL,NULL,NULL,'Kamukunji',1110),
(NULL,NULL,NULL,NULL,NULL,'Kandara',218),
(NULL,NULL,NULL,NULL,NULL,'Kanduyi',617),
(NULL,NULL,NULL,NULL,NULL,'Kangema',10),
(NULL,NULL,NULL,NULL,NULL,'Kangundo',190),
(NULL,NULL,NULL,NULL,NULL,'Kapseret',115),
(NULL,NULL,NULL,NULL,NULL,'Karachuonyo',362),
(NULL,NULL,NULL,NULL,NULL,'Kasarani',613),
(NULL,NULL,NULL,NULL,NULL,'Kathiani',205),
(NULL,NULL,NULL,NULL,NULL,'Keiyo North',257),
(NULL,NULL,NULL,NULL,NULL,'Keiyo South',121),
(NULL,NULL,NULL,NULL,NULL,'Kesses',307),
(NULL,NULL,NULL,NULL,NULL,'Khwisero',244),
(NULL,NULL,NULL,NULL,NULL,'Kiambaa',145),
(NULL,NULL,NULL,NULL,NULL,'Kiambu Town',486),
(NULL,NULL,NULL,NULL,NULL,'Kibish',15),
(NULL,NULL,NULL,NULL,NULL,'Kibra',1758),
(NULL,NULL,NULL,NULL,NULL,'Kibwezi East',150),
(NULL,NULL,NULL,NULL,NULL,'Kibwezi West',344),
(NULL,NULL,NULL,NULL,NULL,'Kieni East',109),
(NULL,NULL,NULL,NULL,NULL,'Kieni West',130),
(NULL,NULL,NULL,NULL,NULL,'Kigumo',34),
(NULL,NULL,NULL,NULL,NULL,'Kiharu',380),
(NULL,NULL,NULL,NULL,NULL,'Kikuyu',389),
(NULL,NULL,NULL,NULL,NULL,'Kilifi North',232),
(NULL,NULL,NULL,NULL,NULL,'Kilifi South',80),
(NULL,NULL,NULL,NULL,NULL,'Kilome',65),
(NULL,NULL,NULL,NULL,NULL,'Kimilili',234),
(NULL,NULL,NULL,NULL,NULL,'Kiminini',503),
(NULL,NULL,NULL,NULL,NULL,'Kinango',131),
(NULL,NULL,NULL,NULL,NULL,'Kinangop',236),
(NULL,NULL,NULL,NULL,NULL,'Kipipiri',71),
(NULL,NULL,NULL,NULL,NULL,'Kipkelion East',128),
(NULL,NULL,NULL,NULL,NULL,'Kipkelion West',143),
(NULL,NULL,NULL,NULL,NULL,'Kirinyaga Central',416),
(NULL,NULL,NULL,NULL,NULL,'Kirinyaga East',289),
(NULL,NULL,NULL,NULL,NULL,'Kirinyaga North/Mwea West',274),
(NULL,NULL,NULL,NULL,NULL,'Kirinyaga South',344),
(NULL,NULL,NULL,NULL,NULL,'Kirinyaga West',229),
(NULL,NULL,NULL,NULL,NULL,'Kisauni',85),
(NULL,NULL,NULL,NULL,NULL,'Kisumu Central',1284),
(NULL,NULL,NULL,NULL,NULL,'Kisumu East',313),
(NULL,NULL,NULL,NULL,NULL,'Kisumu West',331),
(NULL,NULL,NULL,NULL,NULL,'Kitui Central',437),
(NULL,NULL,NULL,NULL,NULL,'Kitui East',72),
(NULL,NULL,NULL,NULL,NULL,'Kitui Rural',58),
(NULL,NULL,NULL,NULL,NULL,'Kitui South',199),
(NULL,NULL,NULL,NULL,NULL,'Kitui West',150),
(NULL,NULL,NULL,NULL,NULL,'Kitutu Chache North',100),
(NULL,NULL,NULL,NULL,NULL,'Kitutu Chache South',1640),
(NULL,NULL,NULL,NULL,NULL,'Koibatek',256),
(NULL,NULL,NULL,NULL,NULL,'Konoin',119),
(NULL,NULL,NULL,NULL,NULL,'Kuresoi North',76),
(NULL,NULL,NULL,NULL,NULL,'Kuresoi South',96),
(NULL,NULL,NULL,NULL,NULL,'Kuria East',184),
(NULL,NULL,NULL,NULL,NULL,'Kuria West',461),
(NULL,NULL,NULL,NULL,NULL,'Kwanza',88),
(NULL,NULL,NULL,NULL,NULL,'Lafey',41),
(NULL,NULL,NULL,NULL,NULL,'Lagdera',20),
(NULL,NULL,NULL,NULL,NULL,'Laikipia East',347),
(NULL,NULL,NULL,NULL,NULL,'Laikipia North',60),
(NULL,NULL,NULL,NULL,NULL,'Laikipia West',417),
(NULL,NULL,NULL,NULL,NULL,'Laisamis',138),
(NULL,NULL,NULL,NULL,NULL,'Lamu East',0),
(NULL,NULL,NULL,NULL,NULL,'Lamu West',233),
(NULL,NULL,NULL,NULL,NULL,'Langata',951),
(NULL,NULL,NULL,NULL,NULL,'Lari',402),
(NULL,NULL,NULL,NULL,NULL,'Likoni',119),
(NULL,NULL,NULL,NULL,NULL,'Likuyani',177),
(NULL,NULL,NULL,NULL,NULL,'Limuru',411),
(NULL,NULL,NULL,NULL,NULL,'Loima',74),
(NULL,NULL,NULL,NULL,NULL,'Loitokitok',364),
(NULL,NULL,NULL,NULL,NULL,'Luanda',180),
(NULL,NULL,NULL,NULL,NULL,'Lugari',103),
(NULL,NULL,NULL,NULL,NULL,'Lunga Lunga',43),
(NULL,NULL,NULL,NULL,NULL,'Lurambi',671),
('level1','KE_1_016',2009,'country','KE','Machakos',913),
(NULL,NULL,NULL,NULL,NULL,'Magarini',124),
(NULL,NULL,NULL,NULL,NULL,'Makadara',228),
('level1','KE_1_017',2009,'country','KE','Makueni',375),
(NULL,NULL,NULL,NULL,NULL,'Malava',92),
(NULL,NULL,NULL,NULL,NULL,'Malindi',265),
(NULL,NULL,NULL,NULL,NULL,'Mandera East',548),
(NULL,NULL,NULL,NULL,NULL,'Mandera North',192),
(NULL,NULL,NULL,NULL,NULL,'Mandera South',164),
(NULL,NULL,NULL,NULL,NULL,'Mandera West',152),
(NULL,NULL,NULL,NULL,NULL,'Manga',170),
(NULL,NULL,NULL,NULL,NULL,'Manyatta',949),
(NULL,NULL,NULL,NULL,NULL,'Marakwet East',250),
(NULL,NULL,NULL,NULL,NULL,'Marakwet West',230),
(NULL,NULL,NULL,NULL,NULL,'Marigat',88),
(NULL,NULL,NULL,NULL,NULL,'Masaba North',105),
(NULL,NULL,NULL,NULL,NULL,'Masinga',130),
(NULL,NULL,NULL,NULL,NULL,'Matayos',440),
(NULL,NULL,NULL,NULL,NULL,'Mathare',875),
(NULL,NULL,NULL,NULL,NULL,'Mathioya',80),
(NULL,NULL,NULL,NULL,NULL,'Mathira East',357),
(NULL,NULL,NULL,NULL,NULL,'Mathira West',215),
(NULL,NULL,NULL,NULL,NULL,'Matuga',127),
(NULL,NULL,NULL,NULL,NULL,'Matungu',187),
(NULL,NULL,NULL,NULL,NULL,'Matungulu',94),
(NULL,NULL,NULL,NULL,NULL,'Mbeere North',137),
(NULL,NULL,NULL,NULL,NULL,'Mbeere South',208),
(NULL,NULL,NULL,NULL,NULL,'Mbita',189),
(NULL,NULL,NULL,NULL,NULL,'Mbooni',219),
(NULL,NULL,NULL,NULL,NULL,'Merti',26),
(NULL,NULL,NULL,NULL,NULL,'Mogotio',91),
(NULL,NULL,NULL,NULL,NULL,'Moiben',116),
(NULL,NULL,NULL,NULL,NULL,'Molo',112),
(NULL,NULL,NULL,NULL,NULL,'Mosop',126),
(NULL,NULL,NULL,NULL,NULL,'Moyale',312),
(NULL,NULL,NULL,NULL,NULL,'Msambweni',220),
(NULL,NULL,NULL,NULL,NULL,'Mt Elgon',94),
(NULL,NULL,NULL,NULL,NULL,'Muhoroni',189),
(NULL,NULL,NULL,NULL,NULL,'Mukurweini',177),
(NULL,NULL,NULL,NULL,NULL,'Mumias East',35),
(NULL,NULL,NULL,NULL,NULL,'Mumias West',141),
(NULL,NULL,NULL,NULL,NULL,'muranga south',210),
(NULL,NULL,NULL,NULL,NULL,'Muthambi',6),
(NULL,NULL,NULL,NULL,NULL,'Mvita',1098),
(NULL,NULL,NULL,NULL,NULL,'Mwala',63),
(NULL,NULL,NULL,NULL,NULL,'Mwatate',36),
(NULL,NULL,NULL,NULL,NULL,'Mwimbi',365),
(NULL,NULL,NULL,NULL,NULL,'Mwingi Central',387),
(NULL,NULL,NULL,NULL,NULL,'Mwingi North',113),
(NULL,NULL,NULL,NULL,NULL,'Mwingi West',156),
(NULL,NULL,NULL,NULL,NULL,'Naivasha',557),
(NULL,NULL,NULL,NULL,NULL,'Nakuru East',500),
(NULL,NULL,NULL,NULL,NULL,'Nakuru North',168),
(NULL,NULL,NULL,NULL,NULL,'Nakuru West',872),
(NULL,NULL,NULL,NULL,NULL,'Nambale',83),
(NULL,NULL,NULL,NULL,NULL,'Nandi Hills',93),
(NULL,NULL,NULL,NULL,NULL,'Narok East',40),
(NULL,NULL,NULL,NULL,NULL,'Narok North',311),
(NULL,NULL,NULL,NULL,NULL,'Narok South',89),
(NULL,NULL,NULL,NULL,NULL,'Narok West',161),
(NULL,NULL,NULL,NULL,NULL,'Navakholo',84),
(NULL,NULL,NULL,NULL,NULL,'Ndaragwa',48),
(NULL,NULL,NULL,NULL,NULL,'Ndhiwa',185),
(NULL,NULL,NULL,NULL,NULL,'Njoro',80),
(NULL,NULL,NULL,NULL,NULL,'North Horr',50),
(NULL,NULL,NULL,NULL,NULL,'Nyakach',450),
(NULL,NULL,NULL,NULL,NULL,'Nyali',191),
('level1','KE_1_046',2009,'country','KE','Nyamira',490),
(NULL,NULL,NULL,NULL,NULL,'Nyamira North',140),
(NULL,NULL,NULL,NULL,NULL,'Nyando',252),
(NULL,NULL,NULL,NULL,NULL,'Nyaribari Chache',259),
(NULL,NULL,NULL,NULL,NULL,'Nyaribari Masaba',91),
(NULL,NULL,NULL,NULL,NULL,'Nyatike',462),
(NULL,NULL,NULL,NULL,NULL,'Nyeri Central',664),
(NULL,NULL,NULL,NULL,NULL,'Nyeri South',469),
(NULL,NULL,NULL,NULL,NULL,'Oljoroorok',48),
(NULL,NULL,NULL,NULL,NULL,'Olkalou',185),
(NULL,NULL,NULL,NULL,NULL,'Pokot Central',64),
(NULL,NULL,NULL,NULL,NULL,'Pokot North',125),
(NULL,NULL,NULL,NULL,NULL,'Pokot South',177),
(NULL,NULL,NULL,NULL,NULL,'Rabai',52),
(NULL,NULL,NULL,NULL,NULL,'Rachuonyo South',246),
(NULL,NULL,NULL,NULL,NULL,'Rangwe',154),
(NULL,NULL,NULL,NULL,NULL,'Rarieda',188),
(NULL,NULL,NULL,NULL,NULL,'Rongai',101),
(NULL,NULL,NULL,NULL,NULL,'Rongo',289),
(NULL,NULL,NULL,NULL,NULL,'Roysambu',783),
(NULL,NULL,NULL,NULL,NULL,'Ruaraka',141),
(NULL,NULL,NULL,NULL,NULL,'Ruiru',243),
(NULL,NULL,NULL,NULL,NULL,'Runyenjes',411),
(NULL,NULL,NULL,NULL,NULL,'Sabatia',172),
(NULL,NULL,NULL,NULL,NULL,'Saboti',128),
(NULL,NULL,NULL,NULL,NULL,'Saku',139),
(NULL,NULL,NULL,NULL,NULL,'Samburu Central',244),
(NULL,NULL,NULL,NULL,NULL,'Samburu East',266),
(NULL,NULL,NULL,NULL,NULL,'Samburu North',80),
(NULL,NULL,NULL,NULL,NULL,'Samia',198),
(NULL,NULL,NULL,NULL,NULL,'Seme',137),
(NULL,NULL,NULL,NULL,NULL,'Shinyalu',370),
(NULL,NULL,NULL,NULL,NULL,'Sigowet/Soin',132),
(NULL,NULL,NULL,NULL,NULL,'Sirisia',66),
(NULL,NULL,NULL,NULL,NULL,'Sotik',244),
(NULL,NULL,NULL,NULL,NULL,'South Mugirango',436),
(NULL,NULL,NULL,NULL,NULL,'Soy',128),
(NULL,NULL,NULL,NULL,NULL,'Starehe',439),
(NULL,NULL,NULL,NULL,NULL,'Suba South',223),
(NULL,NULL,NULL,NULL,NULL,'Subukia',80),
(NULL,NULL,NULL,NULL,NULL,'Suna East',420),
(NULL,NULL,NULL,NULL,NULL,'Suna West',563),
(NULL,NULL,NULL,NULL,NULL,'Tarbaj',20),
('level1','KE_1_006',2009,'country','KE','Taveta',111),
(NULL,NULL,NULL,NULL,NULL,'Teso North',170),
(NULL,NULL,NULL,NULL,NULL,'Teso South',242),
(NULL,NULL,NULL,NULL,NULL,'Tetu',54),
(NULL,NULL,NULL,NULL,NULL,'Tharaka North',35),
(NULL,NULL,NULL,NULL,NULL,'Tharaka South',249),
(NULL,NULL,NULL,NULL,NULL,'Thika Town',899),
(NULL,NULL,NULL,NULL,NULL,'Tiaty East',24),
(NULL,NULL,NULL,NULL,NULL,'Tigania East',211),
(NULL,NULL,NULL,NULL,NULL,'Tigania West',124),
(NULL,NULL,NULL,NULL,NULL,'Tinderet',66),
(NULL,NULL,NULL,NULL,NULL,'Tongaren',114),
(NULL,NULL,NULL,NULL,NULL,'Transmara East',76),
(NULL,NULL,NULL,NULL,NULL,'Transmara West',493),
(NULL,NULL,NULL,NULL,NULL,'Turbo',226),
(NULL,NULL,NULL,NULL,NULL,'Turkana Central',336),
(NULL,NULL,NULL,NULL,NULL,'Turkana East',69),
(NULL,NULL,NULL,NULL,NULL,'Turkana North',45),
(NULL,NULL,NULL,NULL,NULL,'Turkana South',157),
(NULL,NULL,NULL,NULL,NULL,'Turkana West',173),
(NULL,NULL,NULL,NULL,NULL,'Ugenya',89),
(NULL,NULL,NULL,NULL,NULL,'Ugunja',205),
(NULL,NULL,NULL,NULL,NULL,'Uriri',207),
('level1','KE_1_038',2009,'country','KE','Vihiga',290),
(NULL,NULL,NULL,NULL,NULL,'Voi',202),
(NULL,NULL,NULL,NULL,NULL,'Wajir East',432),
(NULL,NULL,NULL,NULL,NULL,'Wajir North',43),
(NULL,NULL,NULL,NULL,NULL,'Wajir South',51),
(NULL,NULL,NULL,NULL,NULL,'Wajir West',55),
(NULL,NULL,NULL,NULL,NULL,'Webuye East',99),
(NULL,NULL,NULL,NULL,NULL,'Webuye West',370),
('level1','KE_1_024',2009,'country','KE','West Pokot',191),
(NULL,NULL,NULL,NULL,NULL,'Westlands',794),
(NULL,NULL,NULL,NULL,NULL,'Wundanyi',94),
(NULL,NULL,NULL,NULL,NULL,'Yatta',174),
('level1','KE_1_030',2009,'country','KE','Baringo',820),
('level1','KE_1_036',2009,'country','KE','Bomet',845),
('level1','KE_1_039',2009,'country','KE','Bungoma',2038),
('level1','KE_1_040',2009,'country','KE','Busia',1314),
('level1','KE_1_028',2009,'country','KE','Elgeyo-Marakwet',858),
('level1','KE_1_014',2009,'country','KE','Embu',1705),
('level1','KE_1_007',2009,'country','KE','Garissa',864),
('level1','KE_1_043',2009,'country','KE','Homa Bay',2006),
('level1','KE_1_011',2009,'country','KE','Isiolo',694),
('level1','KE_1_034',2009,'country','KE','Kajiado',1445),
('level1','KE_1_037',2009,'country','KE','Kakamega',2464),
('level1','KE_1_035',2009,'country','KE','Kericho',1865),
('level1','KE_1_022',2009,'country','KE','Kiambu',3790),
('level1','KE_1_003',2009,'country','KE','Kilifi',1016),
('level1','KE_1_020',2009,'country','KE','Kirinyaga',1552),
('level1','KE_1_045',2009,'country','KE','Kisii',3108),
('level1','KE_1_042',2009,'country','KE','Kisumu',2956),
('level1','KE_1_015',2009,'country','KE','Kitui',1572),
('level1','KE_1_002',2009,'country','KE','Kwale',521),
('level1','KE_1_031',2009,'country','KE','Laikipia',824),
('level1','KE_1_005',2009,'country','KE','Lamu',233),
('level1','KE_1_016',2009,'country','KE','Machakos',2463),
('level1','KE_1_017',2009,'country','KE','Makueni',1316),
('level1','KE_1_009',2009,'country','KE','Mandera',1154),
('level1','KE_1_010',2009,'country','KE','Marsabit',639),
('level1','KE_1_012',2009,'country','KE','Meru',2239),
('level1','KE_1_044',2009,'country','KE','Migori',2792),
('level1','KE_1_001',2009,'country','KE','Mombasa',1839),
(NULL,NULL,NULL,NULL,NULL,'Muranga',997),
('level1','KE_1_047',2009,'country','KE','Nairobi',9504),
('level1','KE_1_032',2009,'country','KE','Nakuru',3144),
('level1','KE_1_029',2009,'country','KE','Nandi',839),
('level1','KE_1_033',2009,'country','KE','Narok',1170),
('level1','KE_1_046',2009,'country','KE','Nyamira',1121),
('level1','KE_1_018',2009,'country','KE','Nyandarua',588),
('level1','KE_1_019',2009,'country','KE','Nyeri',2175),
('level1','KE_1_025',2009,'country','KE','Samburu',590),
('level1','KE_1_041',2009,'country','KE','Siaya',1475),
('level1','KE_1_006',2009,'country','KE','Taita Taveta',443),
('level1','KE_1_004',2009,'country','KE','Tana River',319),
('level1','KE_1_013',2009,'country','KE','Tharaka Nithi',1016),
('level1','KE_1_026',2009,'country','KE','Trans Nzoia',853),
('level1','KE_1_023',2009,'country','KE','Turkana',869),
('level1','KE_1_027',2009,'country','KE','Uasin Gishu',2216),
('level1','KE_1_038',2009,'country','KE','Vihiga',874),
('level1','KE_1_008',2009,'country','KE','Wajir',601),
('level1','KE_1_024',2009,'country','KE','West Pokot',557),
('country','KE',2009,'continent','AFR','Kenya',74283);
      
INSERT into public.sources(geo_level, country_code, table_name, source_title, source_link) VALUES('level1','KE','allNumberOfHospitalBeds','Kenya Master Health Facility List','http://kmhfl.health.go.ke/') on conflict do nothing;
INSERT into public.sources(geo_level, country_code, table_name, source_title, source_link) VALUES('country','KE','allNumberOfHospitalBeds','Kenya Master Health Facility List','http://kmhfl.health.go.ke/') on conflict do nothing;

