-- -------------------------------------------------------------
-- TablePlus 2.12(282)
--
-- https://tableplus.com/
--
-- Database: dominion_api
-- Generation Time: 2020-03-27 10:18:33.4170
-- -------------------------------------------------------------


-- This script only contains the table creation statements and does not fully represent the table in the database. It's still missing: indices, triggers. Do not use it as a backup.

-- Table Definition
CREATE TABLE "public"."sources" (
    "geo_level" varchar(15) NOT NULL,
    "country_code" varchar(10) NOT NULL,
    "table_name" varchar(100) NOT NULL,
    "source_title" varchar(200) NOT NULL,
    "source_link" varchar(250) NOT NULL,
    PRIMARY KEY ("geo_level","country_code","table_name")
);

INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ET', 'allGlobalHealthSecurityIndexes', 'Global Health Security Index, 2019', 'https://www.ghsindex.org/wp-content/uploads/2019/10/2019-Global-Health-Security-Index.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ET', 'allInfectiousDiseaseVulnerabilityIndexes', 'Identifying Future Disease Hot Spots, 2016', 'https://www.rand.org/pubs/research_reports/RR1605.html');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'GH', 'allGlobalHealthSecurityIndexes', 'Global Health Security Index, 2019', 'https://www.ghsindex.org/wp-content/uploads/2019/10/2019-Global-Health-Security-Index.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'GH', 'allInfectiousDiseaseVulnerabilityIndexes', 'Identifying Future Disease Hot Spots, 2016', 'https://www.rand.org/pubs/research_reports/RR1605.html');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'KE', 'allGlobalHealthSecurityIndexes', 'Global Health Security Index, 2019', 'https://www.ghsindex.org/wp-content/uploads/2019/10/2019-Global-Health-Security-Index.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'KE', 'allInfectiousDiseaseVulnerabilityIndexes', 'Identifying Future Disease Hot Spots, 2016', 'https://www.rand.org/pubs/research_reports/RR1605.html');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'KE', 'allPercentageOfHouseholdsWherePlaceForWashingHandsWasObserved', 'Kenya Demographic and Health Survey, 2014', 'https://dhsprogram.com/pubs/pdf/fr308/fr308.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'KE', 'allPercentagePopulationReceivingFreeMedical', 'Kenya Integrated Household Budget Survey, 2016', 'http://statistics.knbs.or.ke/nada/index.php/catalog/88/download/745');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'KE', 'allPopulationWith10YearCvdRiskGreaterOrEqualTo30Percent', 'Kenya STEPwise Survey for Non Communicable Diseases Risk Factors, 2015', 'http://www.health.go.ke/wp-content/uploads/2016/04/Steps-Report-NCD-2015.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allAccessToInformations', 'Afrobarometer Round 7: Survey, 2018', 'http://afrobarometer.org/publications/south-africa-summary-results-2018');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allAllowFarmersRetainLandOwnerships', 'Afrobarometer Round 7: Survey, 2018', 'http://afrobarometer.org/publications/south-africa-summary-results-2018');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allAvgPricePerHectaresPerClass2018S', 'AGRIDS, 2019', 'http://land.agrids.co.za/');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allBenefitedbeneficiaries', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allBenefitedhouseholds', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allDisabledpeoplepartybenefiteds', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allErvenLandOwnershipInHectaresByGenders', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allErvenLandOwnershipInHectaresByNationalities', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allErvenLandOwnershipInHectaresByRaces', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allFemalepartybenefiteds', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allGlobalHealthSecurityIndexes', 'Global Health Security Index, 2019', 'https://www.ghsindex.org/wp-content/uploads/2019/10/2019-Global-Health-Security-Index.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allHectaresTransferredPerProvinceByYears', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allHighestPriceTradedPerClass2018S', 'AGRIDS, 2019', 'http://land.agrids.co.za/');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allInfectiousDiseaseVulnerabilityIndexes', 'Identifying Future Disease Hot Spots, 2016', 'https://www.rand.org/pubs/research_reports/RR1605.html');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allLandAcquisationChallenges', 'Afrobarometer Round 7: Survey, 2018', 'http://afrobarometer.org/publications/south-africa-summary-results-2018');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allLandownershipinhectaresbygenders', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allLandownershipinhectaresbynationalities', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allLandownershipinhectaresbyraces', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allLandToPrioritiseForRedistributions', 'Afrobarometer Round 7: Survey, 2018', 'http://afrobarometer.org/publications/south-africa-summary-results-2018');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allLandTradedAllVsColour2018S', 'AGRIDS, 2019', 'http://land.agrids.co.za/');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allLandTradedColourCostBreakdown2018S', 'AGRIDS, 2019', 'http://land.agrids.co.za/');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allLandTradedColourHectaresBreakdown2018S', 'AGRIDS, 2019', 'http://land.agrids.co.za/');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allLandTradedColourTransactions2018S', 'AGRIDS, 2019', 'http://land.agrids.co.za/');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allLowestPriceTradedPerClass2018S', 'AGRIDS, 2019', 'http://land.agrids.co.za/');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allMaintainWillingBuyerWillingSellerPolicies', 'Afrobarometer Round 7: Survey, 2018', 'http://afrobarometer.org/publications/south-africa-summary-results-2018');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allNumberOfErvenLandOwnersPerGenders', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allNumberOfErvenLandOwnersPerNationalities', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allNumberOfErvenLandOwnersPerRaces', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allNumberoflandownerspergenders', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allNumberoflandownerspernationalities', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allNumberoflandownersperraces', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allNumberofprivatelandownersbycategories', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allNumberofsectionaltitleownersbycategories', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allNumberofsectionaltitleownersbygenders', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allNumberofsectionaltitleownersbynationalities', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allNumberofsectionaltitleownersbyraces', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allNumTransactionsTradedPerClass2018S', 'AGRIDS, 2019', 'http://land.agrids.co.za/');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allPopulationGroup2016S', 'Community Survey, 2016', 'http://cs2016.statssa.gov.za/wp-content/uploads/2016/07/NT-30-06-2016-RELEASE-for-CS-2016-_Statistical-releas_1-July-2016.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allPopulationResidence2009S', 'Census, 2009', 'https://s3-eu-west-1.amazonaws.com/s3.sourceafrica.net/documents/21195/Census-2009.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allPriceTrendsTradedPerClass2018S', 'AGRIDS, 2019', 'http://land.agrids.co.za/');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allPrivatelandownershipinhectarespercategories', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allProjecttransferreds', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allRedistributedlandcostinrands', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allRedistributedlandinhectares', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allRedistributedlandnumhectares', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allRedistributedlandusebreakdowns', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allRestitutionbeneficiaries', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allRestitutionfemaleheadedhhs', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allRestitutionfinancialcompensations', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allRestitutionhectaresacquireds', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allRestitutionhouseholds', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allRestitutionlandcosts', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allRestitutionpeoplewdisabilities', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allSectionaltitleownershipinhectaresnationalities', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allSectionaltitleownershipinhectarespercategories', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allSectionaltitleownershipinhectarespergenders', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allSectionaltitleownershipinhectaresperraces', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allTotalHectaresTradedPerClass2018S', 'AGRIDS, 2019', 'http://land.agrids.co.za/');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allWazimapGeographies', 'Municipal Demarcation Board', 'https://africaopendata.org/dataset/municipal-demarcation-board-national-boundary-data');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allWorkersHostelAccessElectricities', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allWorkersHostelAgeGroups', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allWorkersHostelGenders', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allWorkersHostelGeographies', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allWorkersHostelHandwashingFacilities', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allWorkersHostelOwnerships', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allWorkersHostelPopulationGroups', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allWorkersHostelPopulations', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allWorkersHostelRents', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allWorkersHostelResidentialOwnerships', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allWorkersHostelSsDwellings', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allWorkersHostelWaterSources', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('country', 'ZA', 'allYouthpartybenefiteds', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'KE', 'allPercentagePopulationReceivingFreeMedical', 'Kenya Integrated Household Budget Survey, 2016', 'http://statistics.knbs.or.ke/nada/index.php/catalog/88/download/745');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allAccessToInformations', 'Afrobarometer Round 7: Survey, 2018', 'http://afrobarometer.org/publications/south-africa-summary-results-2018');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allAllowFarmersRetainLandOwnerships', 'Afrobarometer Round 7: Survey, 2018', 'http://afrobarometer.org/publications/south-africa-summary-results-2018');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allAvgPricePerHectaresPerClass2018S', 'AGRIDS, 2019', 'http://land.agrids.co.za/');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allBenefitedbeneficiaries', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allBenefitedhouseholds', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allDisabledpeoplepartybenefiteds', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allErvenLandOwnershipInHectaresByGenders', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allErvenLandOwnershipInHectaresByNationalities', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allErvenLandOwnershipInHectaresByRaces', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allFemalepartybenefiteds', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allHectaresTransferredPerProvinceByYears', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allHighestPriceTradedPerClass2018S', 'AGRIDS, 2019', 'http://land.agrids.co.za/');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allLandAcquisationChallenges', 'Afrobarometer Round 7: Survey, 2018', 'http://afrobarometer.org/publications/south-africa-summary-results-2018');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allLandownershipinhectaresbygenders', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allLandownershipinhectaresbynationalities', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allLandownershipinhectaresbyraces', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allLandToPrioritiseForRedistributions', 'Afrobarometer Round 7: Survey, 2018', 'http://afrobarometer.org/publications/south-africa-summary-results-2018');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allLandTradedAllVsColour2018S', 'AGRIDS, 2019', 'http://land.agrids.co.za/');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allLandTradedColourCostBreakdown2018S', 'AGRIDS, 2019', 'http://land.agrids.co.za/');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allLandTradedColourHectaresBreakdown2018S', 'AGRIDS, 2019', 'http://land.agrids.co.za/');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allLandTradedColourTransactions2018S', 'AGRIDS, 2019', 'http://land.agrids.co.za/');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allLowestPriceTradedPerClass2018S', 'AGRIDS, 2019', 'http://land.agrids.co.za/');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allMaintainWillingBuyerWillingSellerPolicies', 'Afrobarometer Round 7: Survey, 2018', 'http://afrobarometer.org/publications/south-africa-summary-results-2018');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allNumberOfErvenLandOwnersPerGenders', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allNumberOfErvenLandOwnersPerNationalities', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allNumberOfErvenLandOwnersPerRaces', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allNumberoflandownerspergenders', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allNumberoflandownerspernationalities', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allNumberoflandownersperraces', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allNumberofprivatelandownersbycategories', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allNumberofsectionaltitleownersbycategories', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allNumberofsectionaltitleownersbygenders', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allNumberofsectionaltitleownersbynationalities', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allNumberofsectionaltitleownersbyraces', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allNumTransactionsTradedPerClass2018S', 'AGRIDS, 2019', 'http://land.agrids.co.za/');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allPopulationGroup2016S', 'Community Survey, 2016', 'http://cs2016.statssa.gov.za/wp-content/uploads/2016/07/NT-30-06-2016-RELEASE-for-CS-2016-_Statistical-releas_1-July-2016.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allPopulationResidence2009S', 'Census, 2009', 'https://s3-eu-west-1.amazonaws.com/s3.sourceafrica.net/documents/21195/Census-2009.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allPriceTrendsTradedPerClass2018S', 'AGRIDS, 2019', 'http://land.agrids.co.za/');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allPrivatelandownershipinhectarespercategories', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allProjecttransferreds', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allRedistributedlandcostinrands', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allRedistributedlandinhectares', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allRedistributedlandnumhectares', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allRedistributedlandusebreakdowns', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allRestitutionbeneficiaries', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allRestitutionfemaleheadedhhs', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allRestitutionfinancialcompensations', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allRestitutionhectaresacquireds', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allRestitutionhouseholds', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allRestitutionlandcosts', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allRestitutionpeoplewdisabilities', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allSectionaltitleownershipinhectaresnationalities', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allSectionaltitleownershipinhectarespercategories', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allSectionaltitleownershipinhectarespergenders', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allSectionaltitleownershipinhectaresperraces', 'Land Audit Report, 2017', 'http://www.ruraldevelopment.gov.za/publications/land-audit-report/file/6126');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allTotalHectaresTradedPerClass2018S', 'AGRIDS, 2019', 'http://land.agrids.co.za/');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allWazimapGeographies', 'Municipal Demarcation Board', 'https://africaopendata.org/dataset/municipal-demarcation-board-national-boundary-data');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allWorkersHostelAccessElectricities', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allWorkersHostelAgeGroups', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allWorkersHostelGenders', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allWorkersHostelGeographies', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allWorkersHostelHandwashingFacilities', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allWorkersHostelOwnerships', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allWorkersHostelPopulationGroups', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allWorkersHostelPopulations', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allWorkersHostelRents', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allWorkersHostelResidentialOwnerships', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allWorkersHostelSsDwellings', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allWorkersHostelWaterSources', 'General Household Survey, 2018', 'http://www.statssa.gov.za/publications/P0318/P03182018.pdf');
INSERT INTO "public"."sources" ("geo_level", "country_code", "table_name", "source_title", "source_link") VALUES ('level1', 'ZA', 'allYouthpartybenefiteds', 'Annual statistical report for selected service delivery programmes of the Department of Rural Development and Land Reform', 'https://africaopendata.org/dataset/redistribution-and-restitution-in-south-africa-2018/resource/487dcca4-e8ab-4aac-b7a0-9d00a9755f3a?view_id=dcc13ebb-e2e9-46b0-bbe3-505456027fae');
