# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-03 12:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wazimap', '0013_port_to_python3'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbTableChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart', models.CharField(choices=[('column', 'Column'), ('histogram', 'Histogram'), ('line', 'Line'), ('grouped_column', 'Grouped Column'), ('pie', 'Pie Chart')], max_length=32)),
                ('fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150, unique=True), help_text='Comma-separated fields to be included in chart. Choose one field for one Column, Histogram or Pie. And Choose two fields for grouped column', size=None)),
                ('db_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wazimap.DBTable')),
                ('field_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wazimap.FieldTable')),
            ],
        ),
    ]
