# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-05 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hurumap_ke', '0002_auto_20190704_1604'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Charts',
            new_name='Chart',
        ),
    ]
