# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-05 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurumap_ke', '0003_auto_20190705_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for section profile', max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
