# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-05 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hurumap_ke', '0004_chartsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='hurumap_ke.ChartSection'),
        ),
    ]
