# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-08 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurumap_ke', '0005_chart_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='chart',
        ),
        migrations.AddField(
            model_name='chart',
            name='chart_type',
            field=models.CharField(default='column', max_length=32),
            preserve_default=False,
        ),
    ]
