# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-10 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hurumap_ke', '0008_auto_20190709_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='chart_source',
            field=models.CharField(blank=True, help_text='Name for source of Data', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='chart_source_link',
            field=models.CharField(blank=True, help_text='Link to source of data', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='chart',
            name='chart_title',
            field=models.CharField(blank=True, help_text='Descriptive title of this chart', max_length=500, null=True),
        ),
    ]
