# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-16 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominion', '0002_chart_chart_stat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='group_by',
            field=models.CharField(blank=True, help_text='Default is Number', max_length=120, null=True),
        ),
    ]
