# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-17 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominion', '0003_chart_group_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='group_by',
            field=models.CharField(blank=True, help_text='You have choose grouped column chart, which field should the chart be grouped by?', max_length=120, null=True),
        ),
    ]
