# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-17 12:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap', '0013_port_to_python3'),
        ('dominion', '0004_auto_20190717_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(max_length=32)),
                ('fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150, unique=True), help_text='Comma-separated fields to be included in chart. Choose one field for one Column, Histogram or Pie. And Choose two fields for grouped column', size=None)),
                ('title', models.CharField(blank=True, help_text='Descriptive title of this chart', max_length=500, null=True)),
                ('source', models.CharField(blank=True, help_text='Data source', max_length=500, null=True)),
                ('source_link', models.URLField(blank=True, help_text='Link to data source', max_length=500, null=True)),
                ('stat_type', models.CharField(blank=True, help_text='Default is Number', max_length=32, null=True)),
                ('group_by', models.CharField(blank=True, help_text='You have choose grouped column chart, which field should the chart be grouped by?', max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChartSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', help_text='Provide a unique name for list of charts', max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='charts',
            name='parent',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='dominion.ChartSections'),
        ),
        migrations.AddField(
            model_name='charts',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wazimap.DBTable'),
        ),
    ]
