# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-20 17:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('dominion', '0005_auto_20190717_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='charts',
            name='chart_type',
            field=models.CharField(choices=[('column', 'Column'), ('histogram', 'Histogram'), ('line', 'Line'), ('grouped_column', 'Grouped Column'), ('pie', 'Pie')], max_length=32),
        ),
        migrations.AlterField(
            model_name='charts',
            name='fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150, unique=True), size=None),
        ),
        migrations.AlterField(
            model_name='charts',
            name='group_by',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='charts',
            name='stat_type',
            field=models.CharField(blank=True, choices=[('number', 'Number'), ('percentage', 'Percentage')], help_text='Default is Number', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='charts',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wazimap.DBTable', to_field='name'),
        ),
        migrations.AlterField(
            model_name='chartsections',
            name='name',
            field=models.CharField(default='Default Section', help_text='Provide a unique name for list of charts', max_length=1024),
        ),
    ]
