# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-21 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0040_page_draft_title'),
        ('dominion', '0006_auto_20190720_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='db_table',
        ),
        migrations.RemoveField(
            model_name='chart',
            name='section',
        ),
        migrations.RemoveField(
            model_name='charts',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='charts',
            name='table',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='page_ptr',
        ),
        migrations.AlterModelOptions(
            name='chartsection',
            options={},
        ),
        migrations.AlterField(
            model_name='chartsection',
            name='name',
            field=models.CharField(default='Default Section', help_text='Provide a unique name for profile section', max_length=1024),
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
        migrations.DeleteModel(
            name='Charts',
        ),
        migrations.DeleteModel(
            name='ChartSections',
        ),
        migrations.DeleteModel(
            name='EventPage',
        ),
    ]
