# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-21 07:43
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap', '0013_port_to_python3'),
        ('dominion', '0007_auto_20190721_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(choices=[('column', 'Column'), ('histogram', 'Histogram'), ('line', 'Line'), ('grouped_column', 'Grouped Column'), ('pie', 'Pie')], max_length=32)),
                ('fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150, unique=True), size=None)),
                ('title', models.CharField(blank=True, help_text='Descriptive title of this chart', max_length=500, null=True)),
                ('source', models.CharField(blank=True, help_text='Data source', max_length=500, null=True)),
                ('source_link', models.URLField(blank=True, help_text='Link to data source', max_length=500, null=True)),
                ('stat_type', models.CharField(blank=True, choices=[('number', 'Number'), ('percentage', 'Percentage')], help_text='Default is Number', max_length=32, null=True)),
                ('group_by', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='chartsection',
            name='name',
            field=models.CharField(default='Default Section', help_text='Provide a unique name for profile section', max_length=1024, unique=True),
        ),
        migrations.AddField(
            model_name='chart',
            name='section',
            field=models.ForeignKey(help_text='Select profile section where the chart belongs to', on_delete=django.db.models.deletion.CASCADE, to='dominion.ChartSection', to_field='name'),
        ),
        migrations.AddField(
            model_name='chart',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wazimap.DBTable', to_field='name'),
        ),
    ]
