from django import forms

Grade_Options = [('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('S', 'S')]
Subject_Options = [('Accountacy','Accountancy'),('Advance Mathematics', 'Advance Mathematics'),('Agriculture','Agriculture'), ('Arabic Language','Arabic Language'),
('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('Commerce', 'Commerce'),('Computer Science', 'Computer Science'), ('Economics','Economics'), ('English Language','English Language'),
('French Language', 'French Language'), ('Food and Human Nutrition','Food & Human Nutrition'), ('Geography','Geography'), ('History','History'), ('Kiswahili','Kiswahili'),('Physics','Physics'),]

Major_Options = [
"Political Science"
"Telecommucation\, Engineering"
"Sociology"
"Natural Resources"
"Science\, Education"
"Medicine"
"Information Technology"
"Business Administration\, Procurement"
"Engineering\, Agritechnology"
"Computer science"
"Information and Records Management"
"Business Adminiistration\, Finance"
"Accountancy\, Finance"
"Computer Science\, Engineering"
"Nursing\, Education\, Nursing Education"
"Medicine\, Mental Health\, Health Studies"
"Education\, Religious Studies\, Religious Education"
"Law"
"Philosophy\, Education"
"Botanical Science"
"Religious Studies\, Theology"
"Psychology\, Counselling"
"Health Systems Management"
"Commerce\, Accounitng\, Education"
"Telecommunications"
"Divinity\, Religious Studies"
"Religous Studies\, Religious Education\, Education"
"Tourism"
"Education\, Child Education"
"Business Studies\, Business Administration"
"Engineering\, Computer Engineering"
"Computer Science\, Information Systems"
"Psychology"
"Human Resources\, Business Administration"
"Education\, Kiswahili"
"Actuarial Science"
"Accounting\, Finance"
"Physical Education"
"Agronomy"
"Economics\, Statistics"
"Marketing\, Business Studies"
"Education\, Biology\, "
"Mathematics\, Statistics"
"Library Information Studies"
"Environmnet Studies"
"Chemistry"
"Arts"
"Environment Studies"
"Pharmacy"
"Interior Design"
"Social Work"
"Education\, Physics\, Computer Science"
"Medicines\, Physiotherapy"
"Information Management"
"Molecular Biology"
"Data Management"
"Islaminc Studies\, Religious Studies\, Education\, Religious Education"
"Education\, Physics\, Chemistry"
"Procurement"
"Taxation"
"Mathematics\, Education\, Science Education"
"Anthropology\, Tourism"
"Archaelogy"
"Agriculture"
"Architecture"
"Public Relations"
"Regional Development Planning"
"Education\, Commerce"
"Food Technology"
"House Planning"
"Petroleum Geology"
"Education\, Phyisics\, Mathematics"
"Family"
"Education\, Community Education"
"Zoology"
"Business Administration\, International Business"
"Medical Technology"
"Enterpreneurship\, Business Studies"
"Environmnet Studies\, Education"
"Social Work\, Sociology"
"Agriculture\, Finance"
"Economics\, Finance"
"Religious Studies\, Education"
"Social Work\, Counselling"
"Irrigation"
"Social Protection"
"Business Administration\, Accounting"
"Computer Science"
"Filming"
"Business Administration\, Marketing"
"Education\, Mathematics\, Computer Science"
"Economics"
"Multimedia Technology"
"Computer Engineering\, Engineering"
"African Studies\, History"
"Science\, Geology"
"Nutrition"
"Accounting\, Business Studies"
"Public Relations\, Marketing"
"Forestry"
"Accounting"
"Chemistry\, Clinical Chemistry"
"Business Studies\, Marketing"
"Range Management"
"Arts\, Education"
"Marketing\, Enterpreneurship"
"Art"
"Education\, Science"
"Philosophy\, Religious Studies"
"Educatuin\, Theology\, Religious Studies"
"Psychology Education"
"Geology"
"Geoinformatics"
"Computer Engineering\, Engineering\, Information Technology"
"Agribusiness\, Agriculture"
"Journalism"
"Business Administration\, Enterpremeurs"
"History"
"Informatics"
"Law\, Shariah\, Islamic Studies"
"Information Systems"
"Marketing"
"Agriculture\, Agribusiness\, Economics"
"Education\, Mathematics"
"Acccountancy\, Finance"
"Nursing"
"Accounting\, Finance\, information Technology"
"Art\, Designer"
"Geology\, Engineering"
"Education\, Business Studies\, Accounting"
"Surveying"
"Information Security"
"Music"
"Counselling\, Psychology"
"Finance"
"International Relation"
"Development Studies"
"Banking and Finance"
"Business Studies\, Accounting"
"Education"
"Building Economics"
"Sociology\, Social Work"
"Religious Studies"
"Law Enforcement"
"Literature"
"Information Managemnt"
"Science"
"Conflict Resolution"
"Business Studies\, Economics"
"Mass Communication"
"Theology\, Religious Studies"
"Business Admnistration\, Business Studies"
"Economics\, Mathematics\, Education"
"Business Studies\, Accounting\, Finance"
"Human Resources"
"Education\, Physics\, Mathematics"
"Statistics"
"Law\, Shariah"
"Geomatics"
"Anthropology"
"Engineering"
"Biotechnology"
"Education\, Counselling"
"Land Management"
"Production and Operation Management"
"Aquatic Science"
"Education\, Religious Studies"
"Tourism\, Nature"
"Business Studies"
"Language"
"Accountancy"
"Philosophy"
"Electronic Science"
"Education\, Arts"
"Commerce\, Education"
"Science Education\, Education"
"language"
"Health Science"
"Commerce"
"Education\, Business Administration"
"Philosophy\, Political Science"
"Textile Design"
"Real Estate"
"Business Administration"
"Wildlife"
"Local Government Management"
"Microbiology"
"Banking"
"Energy Resources"
"Urban and Regional Planning"
"Language\, Education"
"Kiswahili"
"Biology"
"Business Studies\, Business Administration\, Education"
"Laboratory sciences"
"Public Administration"
"Mathematics\, Education\, Information Technology"
"Education\, Science Education"
"Property Management"
]





class InputForm(forms.Form):
    grades = forms.CharField(label='gender', widget=forms.Select(choices=Grade_Options, attrs={'class': 'form-control', 'id': 'sub-grade'}), required=False)
    subjects = forms.CharField(label='gender', widget=forms.Select(choices=Subject_Options, attrs={'class': 'form-control', 'id': 'sub-name'}), required=False)
