# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 13:24
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'django_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniversityFinder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(blank=True, max_length=100, null=True)),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('major_name', models.CharField(blank=True, max_length=500, null=True)),
                ('compulsory_alevel', django.contrib.postgres.fields.hstore.HStoreField()),
                ('compulsory_olevel', django.contrib.postgres.fields.hstore.HStoreField()),
                ('other_alevel', django.contrib.postgres.fields.hstore.HStoreField()),
                ('other_olevel', django.contrib.postgres.fields.hstore.HStoreField()),
                ('total_point', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'university_finder',
                'managed': False,
            },
        ),
    ]
