from wazimap.data.tables import FieldTable

FieldTable(['private land ownership in hectares per category'], universe=None)
FieldTable(['number of private land owners by category'], universe=None)
FieldTable(['land ownership in hectares by race'], universe=None)
FieldTable(['number of land owners per race'], universe=None)
FieldTable(['land ownership in hectares by gender'], universe=None)
FieldTable(['number of land owners per gender'], universe=None)
FieldTable(['land ownership in hectares by nationality'], universe=None)
FieldTable(['number of land owners per nationality'], universe=None)
FieldTable(['erven land ownership in hectares by race'], universe=None)
FieldTable(['number of erven land owners per race'], universe=None)
FieldTable(['erven land ownership in hectares by gender'], universe=None)
FieldTable(['number of erven land owners per gender'], universe=None)
FieldTable(['erven land ownership in hectares by nationality'], universe=None)
FieldTable(['number of erven land owners per nationality'], universe=None)
FieldTable(['sectional title ownership in hectares per category'], universe=None)
FieldTable(['number of sectional title owners by category'], universe=None)
FieldTable(['sectional title ownership in hectares per race'], universe=None)
FieldTable(['number of sectional title owners by race'], universe=None)
FieldTable(['sectional title ownership in hectares per gender'], universe=None)
FieldTable(['number of sectional title owners by gender'], universe=None)
FieldTable(['sectional title ownership in hectares per nationality'], universe=None)
FieldTable(['number of sectional title owners by nationality'], universe=None)

#Redistribution Data
FieldTable(['number of projects', 'number of households', 'number of beneficiaries'], universe=None)
