from wazimap.data.tables import FieldTable

FieldTable(['private land ownership in hectares per category'], year='2016')
FieldTable(['number of private land owners by category'], year='2016')
FieldTable(['land ownership in hectares by race'], year='2016')
FieldTable(['number of land owners per race'], year='2016')
FieldTable(['land ownership in hectares by gender'], year='2016')
FieldTable(['number of land owners per gender'], year='2016')
FieldTable(['land ownership in hectares by nationality'], year='2016')
FieldTable(['number of land owners per nationality'], year='2016')
FieldTable(['erven land ownership in hectares by race'], year='2016')
FieldTable(['number of erven land owners per race'], year='2016')
FieldTable(['erven land ownership in hectares by gender'], year='2016')
FieldTable(['number of erven land owners per gender'], year='2016')
FieldTable(['erven land ownership in hectares by nationality'], year='2016')
FieldTable(['number of erven land owners per nationality'], year='2016')
FieldTable(['sectional title ownership in hectares per category'], year='2016')
FieldTable(['number of sectional title owners by category'], year='2016')
FieldTable(['sectional title ownership in hectares per race'], year='2016')
FieldTable(['number of sectional title owners by race'], year='2016')
FieldTable(['sectional title ownership in hectares per gender'], year='2016')
FieldTable(['number of sectional title owners by gender'], year='2016')
FieldTable(['sectional title ownership in hectares per nationality'], year='2016')
FieldTable(['number of sectional title owners by nationality'], year='2016')
