from wazimap.data.tables import FieldTable

FieldTable(['private land ownership in hectares per category'], universe='Private Land')
FieldTable(['number of private land owners by category'], universe='Private Land')
FieldTable(['land ownership in hectares by race'], universe='Private Land')
FieldTable(['number of land owners per race'], universe='Private Land')
FieldTable(['land ownership in hectares by gender'], universe='Private Land')
FieldTable(['number of land owners per gender'], universe='Private Land')
FieldTable(['land ownership in hectares by nationality'], universe='Private Land')
FieldTable(['number of land owners per nationality'], universe='Private Land')
FieldTable(['erven land ownership in hectares by race'], universe='Erven Land')
FieldTable(['number of erven land owners per race'], universe='Erven Land')
FieldTable(['erven land ownership in hectares by gender'], universe='Erven Land')
FieldTable(['number of erven land owners per gender'], universe='Erven Land')
FieldTable(['erven land ownership in hectares by nationality'], universe='Erven Land')
FieldTable(['number of erven land owners per nationality'], universe='Erven Land')
FieldTable(['sectional title ownership in hectares per category'], universe='Sectional Title')
FieldTable(['number of sectional title owners by category'], universe='Sectional Title')
FieldTable(['sectional title ownership in hectares per race'], universe='Sectional Title')
FieldTable(['number of sectional title owners by race'], universe='Sectional Title')
FieldTable(['sectional title ownership in hectares per gender'], universe='Sectional Title')
FieldTable(['number of sectional title owners by gender'], universe='Sectional Title')
FieldTable(['sectional title ownership in hectares per nationality'], universe='Sectional Title')
FieldTable(['number of sectional title owners by nationality'], universe='Sectional Title')

#Redistribution Data
FieldTable(['redistributed land use breakdown'], universe='Land Redistribution', year='2016')
FieldTable(['redistributed land in hectares'], universe='Land Redistribution', year='2016')
